# The URL the site will be built for
base_url = "https://nilenso.com"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
tabs = [
    {name="home",path="/"},
    {name="work",path="/work/"},
    {name="conference talks",path="/conference-talks/"},
    {name="people",path="/people/"},
    {name="jobs",path="/jobs/"},
    {name="contact",path="/contact/"}
]
