# The URL the site will be built for
base_url = "https://nilenso.com"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
tabs = [
    {name="work",path="/work/",nav=true},
    {name="conference talks",path="/conference-talks/",nav=false},
    {name="people",path="/people/",nav=true},
    {name="jobs",path="/jobs/",nav=true},
    {name="blog",path="http://blog.nilenso.com/",nav=true},
    {name="alumni",path="/alumni/",nav=false},
    {name="contact",path="#contact",nav=true},
    {name="senior developer",path="/jobs/senior-developer/",nav=false}
]
